
/**
 * This file was generated by the JPA Modeler
 */
package Entities;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * @author a
 */
@Entity
public class Organisation implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    private String PostCode;

    @Basic
    private String Name;

    @Basic
    private String PostalAddress;

    @Basic
    private String Activity;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPostCode() {
        return this.PostCode;
    }

    public void setPostCode(String PostCode) {
        this.PostCode = PostCode;
    }

    public String getName() {
        return this.Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    public String getPostalAddress() {
        return this.PostalAddress;
    }

    public void setPostalAddress(String PostalAddress) {
        this.PostalAddress = PostalAddress;
    }

    public String getActivity() {
        return this.Activity;
    }

    public void setActivity(String Activity) {
        this.Activity = Activity;
    }

}
