/**
 * This file was generated by the JPA Modeler
 */
package Entities;

import oyei.SUMS.Registration.entities.Person;
import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.validation.constraints.NotNull;

/**
 * @author a
 */
@Entity
@NamedQueries({
    @NamedQuery(name="FindAllSupervisor", query= "SELECT sv FROM Staff sv WHERE sv.IsSupervisor = TRUE"),
    @NamedQuery(name="GetSelectedStaff", query= "SELECT s FROM Staff s WHERE s.id = :staffID")
})
public class Staff implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    private String Staffnumber;

    @Column(nullable = false)
    @Basic
    @NotNull
    private boolean IsCoordinator;

    @Column(nullable = false)
    @Basic
    @NotNull
    private boolean IsAdministrator;

    @Column(nullable = false)
    @Basic
    @NotNull
    private boolean IsSupervisor;

    @OneToOne(targetEntity = Person.class)
    private Person person;
    
    @OneToMany(targetEntity = FinalProject.class)
    private List<FinalProject> finalProject;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getStaffnumber() {
        return this.Staffnumber;
    }

    public void setStaffnumber(String Staffnumber) {
        this.Staffnumber = Staffnumber;
    }

    public boolean isIsCoordinator() {
        return this.IsCoordinator;
    }

    public void setIsCoordinator(boolean IsCoordinator) {
        this.IsCoordinator = IsCoordinator;
    }

    public boolean isIsAdministrator() {
        return this.IsAdministrator;
    }

    public void setIsAdministrator(boolean IsAdministrator) {
        this.IsAdministrator = IsAdministrator;
    }

    public boolean isIsSupervisor() {
        return IsSupervisor;
    }

    public void setIsSupervisor(boolean IsSupervisor) {
        this.IsSupervisor = IsSupervisor;
    }
    public Person getPerson() {
        return this.person;
    }

    public void setPerson(Person person) {
        this.person = person;
    }

    public List<FinalProject> getFinalProject() {
        return finalProject;
    }

    public void setFinalProject(List<FinalProject> finalProject) {
        this.finalProject = finalProject;
    }
    

}
