/**
 * This file was generated by the JPA Modeler
 */
package ramazan.SUMS.Monitoring.entities;

import java.io.Serializable;
import java.util.List;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Temporal;

/**
 * @author a
 */
@Entity
@NamedQueries({
    @NamedQuery(name = "Project.cohort", query
            = "SELECT s FROM Staff  s WHERE s.person.cohort.id= :cohortid"),
    @NamedQuery(name = "Staff.findStaffwithProjectId", query
            = "SELECT s FROM Staff s JOIN S.finalProject fp where fp.id =:projectid"),
    @NamedQuery(name = "Project.findByStudentId",
            query = "SELECT ap FROM AllocatedProject ap WHERE ap.student.id = :studentid")
})

public class Milestone implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Basic
    private String Description;
    

    @Basic
    @Temporal(javax.persistence.TemporalType.TIMESTAMP)
    private Date DueDate;

    @Basic
    @Temporal(javax.persistence.TemporalType.TIMESTAMP)
    private Date ActiveDate;

    @Basic
    private String Status;
    @Basic
    private String Comment;
    @Basic
    private String FilePath;
    @Basic
    private int Mark;
    @Basic
    private String FileContext;
    @Basic
    @Temporal(javax.persistence.TemporalType.TIMESTAMP)
    private Date SubmittedDate;

    @OneToMany(targetEntity = MilestoneFeedback.class)
    private List<MilestoneFeedback> feedbacks;

    public int getMark() {
        return Mark;
    }

    public void setMark(int Mark) {
        this.Mark = Mark;
    }

    public Date getDueDate() {
        return DueDate;
    }

    public void setDueDate(Date DueDate) {
        this.DueDate = DueDate;
    }

    public Date getActiveDate() {
        return ActiveDate;
    }

    public void setActiveDate(Date ActiveDate) {
        this.ActiveDate = ActiveDate;
    }

    public Date getSubmittedDate() {
        return SubmittedDate;
    }

    public void setSubmittedDate(Date SubmittedDate) {
        this.SubmittedDate = SubmittedDate;
    }

    public String getFileContext() {
        return FileContext;
    }

    public void setFileContext(String FileContext) {
        this.FileContext = FileContext;
    }

    public String getComment() {
        return Comment;
    }

    public void setComment(String Comment) {
        this.Comment = Comment;
    }

    public String getFilePath() {
        return FilePath;
    }

    public void setFilePath(String FilePath) {
        this.FilePath = FilePath;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDescription() {
        return this.Description;
    }

    public void setDescription(String Description) {
        this.Description = Description;
    }

    public String getStatus() {
        return this.Status;
    }

    public void setStatus(String Status) {
        this.Status = Status;
    }

    public List<MilestoneFeedback> getFeedbacks() {
        return this.feedbacks;
    }

    public void setFeedbacks(List<MilestoneFeedback> feedbacks) {
        this.feedbacks = feedbacks;
    }

}
