/**
 * This file was generated by the JPA Modeler
 */
package ramazan.SUMS.Monitoring.entities;

import Entities.Staff;
import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Temporal;

/**
 * @author a
 */
@Entity
public class MilestoneFeedback implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    private String comment;

    @Basic
    @Temporal(javax.persistence.TemporalType.TIMESTAMP)
    private Date commentDate;
    @Basic
    @Temporal(javax.persistence.TemporalType.TIMESTAMP)
    private Date commentActivateDate;

    @OneToOne(targetEntity = Staff.class)
    private Staff staff;

    public Date getCommentActivateDate() {
        return commentActivateDate;
    }

    public void setCommentActivateDate(Date commentActivateDate) {
        this.commentActivateDate = commentActivateDate;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public Date getCommentDate() {
        return commentDate;
    }

    public void setCommentDate(Date commentDate) {
        this.commentDate = commentDate;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    

    public Staff getStaff() {
        return this.staff;
    }

    public void setStaff(Staff staff) {
        this.staff = staff;
    }

}
